use crate::ir::block::BasicBlock;
use crate::ir::func::Fn;
use crate::ir::instr::*;
use crate::ir::module::Module;
use crate::ir::thunk::Thunk;
use crate::ir::types::*;
use std::fmt::Write;

pub fn generate(module: &Module) -> Result<String, String> {
    let mut out = String::new();
    let mut ctx = LlvmCtx::new();

    writeln!(out, "; Dew IR → LLVM IR translation").ok();
    writeln!(out, "; Generated by dew compiler").ok();
    writeln!(out).ok();

    // Type definitions
    emit_type_defs(module, &mut out, &mut ctx)?;
    // External declarations
    emit_externals(&mut out);
    // Thunk cells + force functions
    for thunk in &module.thunks {
        emit_thunk_cell(thunk, &mut out, &ctx)?;
    }
    for thunk in &module.thunks {
        emit_thunk_force(thunk, &module.thunks, &module.fns, &mut out, &mut ctx)?;
    }
    // Function definitions
    for func in &module.fns {
        emit_fn(func, &module.thunks, &module.fns, &mut out, &mut ctx)?;
    }
    Ok(out)
}

struct LlvmCtx {
    struct_map: std::collections::HashMap<String, usize>,
    enum_map: std::collections::HashMap<String, usize>,
    label_counter: usize,
}

impl LlvmCtx {
    fn new() -> Self {
        LlvmCtx { struct_map: std::collections::HashMap::new(), enum_map: std::collections::HashMap::new(), label_counter: 0 }
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let l = format!("{}{}", prefix, self.label_counter);
        self.label_counter += 1;
        l
    }
}

fn ir_type_to_llvm(ty: &IrType) -> String {
    match ty {
        IrType::Int => "i64".into(),
        IrType::Bool => "i1".into(),
        IrType::Char => "i32".into(),
        IrType::Unit => "void".into(),
        IrType::Struct(name) => format!("%struct.{}", name),
        IrType::Enum(name) => format!("%enum.{}", name),
        IrType::Fun(_, ret) => ir_type_to_llvm(ret),
        IrType::Tuple(_) => "i64".into(),
        IrType::Array(t, n) => format!("[{} x {}]", n, ir_type_to_llvm(t)),
        IrType::ThunkRef(_) => "ptr".into(),
    }
}

fn emit_type_defs(module: &Module, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    for (i, s) in module.types.structs.iter().enumerate() {
        ctx.struct_map.insert(s.name.clone(), i);
        let fields: Vec<String> = s.fields.iter().map(|(_, t)| ir_type_to_llvm(t)).collect();
        writeln!(out, "%struct.{} = type {{ {} }}", s.name, fields.join(", ")).ok();
    }
    for (i, e) in module.types.enums.iter().enumerate() {
        ctx.enum_map.insert(e.name.clone(), i);
        let max_payload = e.variants.iter()
            .map(|v| v.fields.iter().map(|(_, t)| ir_type_to_llvm(t)).collect::<Vec<_>>().join(", "))
            .max_by_key(|s| s.len())
            .unwrap_or_default();
        let payload_type = if max_payload.is_empty() { "i64".into() } else { format!("{{ {} }}", max_payload) };
        writeln!(out, "%enum.{} = type {{ i64, {} }}", e.name, payload_type).ok();
    }
    Ok(())
}

fn emit_externals(out: &mut String) {
    writeln!(out, "declare i32 @printf(ptr, ...)").ok();
    writeln!(out, "declare i32 @scanf(ptr, ...)").ok();
    writeln!(out, "declare i32 @putchar(i32)").ok();
    writeln!(out, "declare i32 @getchar()").ok();
    writeln!(out, "declare ptr @malloc(i64)").ok();
    writeln!(out, "declare void @free(ptr)").ok();
    writeln!(out, "declare void @llvm.trap()").ok();
    writeln!(out).ok();
}

fn emit_thunk_cell(thunk: &Thunk, out: &mut String, _ctx: &LlvmCtx) -> Result<(), String> {
    let val_type = ir_type_to_llvm(&thunk.result_type);
    writeln!(out, "%thunk.{} = type {{ i64, {} }}", thunk.name, val_type).ok();
    writeln!(out, "@{}.cell = global %thunk.{} zeroinitializer", thunk.name, thunk.name).ok();
    writeln!(out).ok();
    Ok(())
}

fn emit_thunk_force(thunk: &Thunk, all_thunks: &[Thunk], all_fns: &[Fn], out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    let ret_ty = ir_type_to_llvm(&thunk.result_type);
    writeln!(out, "define {} @force_{}() {{", ret_ty, thunk.name).ok();

    writeln!(out, "entry:").ok();
    writeln!(out, "  %state.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 0", thunk.name, thunk.name).ok();
    writeln!(out, "  %state = load i64, ptr %state.ptr").ok();
    writeln!(out, "  %is_susp = icmp eq i64 %state, 0").ok();
    writeln!(out, "  br i1 %is_susp, label %eval, label %check_eval").ok();

    writeln!(out, "check_eval:").ok();
    writeln!(out, "  %is_eval = icmp eq i64 %state, 1").ok();
    writeln!(out, "  br i1 %is_eval, label %cycle, label %cached").ok();

    writeln!(out, "eval:").ok();
    writeln!(out, "  store i64 1, ptr %state.ptr").ok();

    for instr in &thunk.blocks.first().map(|b| b.instrs.clone()).unwrap_or_default() {
        emit_llvm_instr(&instr, all_thunks, all_fns, out, ctx)?;
    }

    let result_reg = thunk.blocks.first()
        .and_then(|b| b.instrs.last())
        .map(|i| match i { Instr::Lit(r, _) | Instr::Add(r, ..) | Instr::Sub(r, ..) | Instr::Mul(r, ..) | Instr::Div(r, ..) | Instr::Rem(r, ..) | Instr::Call(r, ..) | Instr::Force(r, ..) => *r, _ => 0 })
        .unwrap_or(0);

    writeln!(out, "  %val.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", thunk.name, thunk.name).ok();
    writeln!(out, "  store {} %r{}, ptr %val.ptr", ret_ty, result_reg).ok();
    writeln!(out, "  store i64 2, ptr %state.ptr").ok();
    writeln!(out, "  ret {} %r{}", ret_ty, result_reg).ok();

    writeln!(out, "cycle:").ok();
    writeln!(out, "  call void @llvm.trap()").ok();
    writeln!(out, "  unreachable").ok();

    writeln!(out, "cached:").ok();
    writeln!(out, "  %val.ptr2 = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", thunk.name, thunk.name).ok();
    writeln!(out, "  %cached = load {}, ptr %val.ptr2", ret_ty).ok();
    writeln!(out, "  ret {} %cached", ret_ty).ok();

    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_fn(func: &Fn, all_thunks: &[Thunk], all_fns: &[Fn], out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    let ret_ty = ir_type_to_llvm(&func.return_type);
    let params: Vec<String> = func.params.iter()
        .map(|(r, t)| format!("{} %r{}", ir_type_to_llvm(t), r))
        .collect();
    writeln!(out, "define {} @{}({}) {{", ret_ty, func.name, params.join(", ")).ok();

    for block in &func.blocks {
        writeln!(out, "{}:", block.label).ok();
        for instr in &block.instrs {
            emit_llvm_instr(instr, all_thunks, all_fns, out, ctx)?;
        }
        emit_terminator(&block.terminator, &func.return_type, out)?;
    }
    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_llvm_instr(instr: &Instr, _thunks: &[Thunk], fns: &[Fn], out: &mut String, _ctx: &mut LlvmCtx) -> Result<(), String> {
    match instr {
        Instr::Lit(r, v) => {
            match v {
                LitValue::Int(n) => writeln!(out, "  %r{} = add i64 0, {}", r, n).ok(),
                LitValue::Bool(b) => writeln!(out, "  %r{} = add i1 0, {}", r, if *b { "true" } else { "false" }).ok(),
                LitValue::Char(c) => writeln!(out, "  %r{} = add i32 0, {}", r, *c as u32).ok(),
            };
        }
        Instr::Add(r, a, b) => { writeln!(out, "  %r{} = add i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Sub(r, a, b) => { writeln!(out, "  %r{} = sub i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Mul(r, a, b) => { writeln!(out, "  %r{} = mul i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Div(r, a, b) => { writeln!(out, "  %r{} = sdiv i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Rem(r, a, b) => { writeln!(out, "  %r{} = srem i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Lt(r, a, b) => { writeln!(out, "  %r{} = icmp slt i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Gt(r, a, b) => { writeln!(out, "  %r{} = icmp sgt i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Le(r, a, b) => { writeln!(out, "  %r{} = icmp sle i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Ge(r, a, b) => { writeln!(out, "  %r{} = icmp sge i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Eq(r, a, b) => { writeln!(out, "  %r{} = icmp eq i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Ne(r, a, b) => { writeln!(out, "  %r{} = icmp ne i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::And(r, a, b) => { writeln!(out, "  %r{} = and i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Or(r, a, b) => { writeln!(out, "  %r{} = or i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Not(r, a) => { writeln!(out, "  %r{} = xor i1 %r{}, true", r, a).ok(); }
        Instr::Call(r, target, args) => {
            match target {
                CallTarget::Static(name) => {
                    let callee = fns.iter().find(|f| &f.name == name).ok_or("fn not found")?;
                    let ret_ty = ir_type_to_llvm(&callee.return_type);
                    let arg_str: Vec<String> = args.iter().enumerate()
                        .map(|(i, reg)| format!("{} %r{}", ir_type_to_llvm(&callee.params.get(i).map(|(_, t)| t.clone()).unwrap_or(IrType::Int)), reg))
                        .collect();
                    writeln!(out, "  %r{} = call {} @{}({})", r, ret_ty, name, arg_str.join(", ")).ok();
                }
                CallTarget::Dynamic(_) => { writeln!(out, "  ; dynamic call (not implemented)").ok(); }
            }
        }
        Instr::Force(r, target) => {
            let name = match target {
                ForceTarget::Static(n) => n.clone(),
                ForceTarget::Dynamic(_) => "unknown".into(),
            };
            writeln!(out, "  %r{} = call i64 @force_{}()", r, name).ok();
        }
        Instr::Stdout(r) => {
            writeln!(out, "  call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 %r{})", r).ok();
        }
        Instr::Stdin(r) => {
            writeln!(out, "  %r{}_ptr = alloca i64", r).ok();
            writeln!(out, "  call i32 (ptr, ...) @scanf(ptr @.fmt_int, ptr %r{}_ptr)", r).ok();
            writeln!(out, "  %r{} = load i64, ptr %r{}_ptr", r, r).ok();
        }
        Instr::Phi(r, pairs) => {
            let p: Vec<String> = pairs.iter()
                .map(|(v, l)| format!("%r{}, %{}", v, l))
                .collect();
            writeln!(out, "  %r{} = phi i64 [{}]", r, p.join("], [")).ok();
        }
        Instr::StructCons(r, name, fields) => {
            let f: Vec<String> = fields.iter().map(|f| format!("i64 %r{}", f)).collect();
            writeln!(out, "  %r{} = insertvalue %struct.{} undef, {}, 0", r, name, f.first().unwrap_or(&"i64 0".into())).ok();
            for (i, fv) in fields.iter().skip(1).enumerate() {
                writeln!(out, "  %r{} = insertvalue %struct.{} %r{}, i64 %r{}, {}", r, name, r, fv, i + 1).ok();
            }
        }
        _ => { writeln!(out, "  ; unimplemented instruction").ok(); }
    }
    Ok(())
}

fn emit_terminator(t: &Terminator, ret_ty: &IrType, out: &mut String) -> Result<(), String> {
    match t {
        Terminator::Ret(r) => {
            let ty = ir_type_to_llvm(ret_ty);
            writeln!(out, "  ret {} %r{}", ty, r).ok();
        }
        Terminator::Br(cond, t_label, f_label) => {
            writeln!(out, "  br i1 %r{}, label %{}, label %{}", cond, t_label, f_label).ok();
        }
        Terminator::Jmp(label) => {
            writeln!(out, "  br label %{}", label).ok();
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_simple_module() {
        let mut module = Module::new();
        let mut f = Fn::new("main".into(), vec![], IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(42)));
        block.terminator = Terminator::Ret(0);
        f.blocks.push(block);
        module.fns.push(f);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("define i64 @main"));
        assert!(llvm.contains("ret i64 %r0"));
    }

    #[test]
    fn generate_with_thunk() {
        let mut module = Module::new();
        let mut t = Thunk::new("x".into(), IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(2026)));
        block.terminator = Terminator::Ret(0);
        t.blocks.push(block);
        module.thunks.push(t);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("@x.cell"));
        assert!(llvm.contains("define i64 @force_x"));
    }
}
