use crate::ir::block::BasicBlock;
use crate::ir::func::Fn;
use crate::ir::instr::*;
use crate::ir::module::Module;
use crate::ir::thunk::Thunk;
use crate::ir::types::*;
use std::fmt::Write;

pub fn generate(module: &Module) -> Result<String, String> {
    let mut out = String::new();
    let mut ctx = LlvmCtx::new();

    writeln!(out, "; Dew IR → LLVM IR translation").ok();
    writeln!(out, "; Generated by dew compiler").ok();
    writeln!(out).ok();

    // Type definitions
    emit_type_defs(module, &mut out, &mut ctx)?;
    // External declarations
    emit_externals(&mut out);
    // Thunk cells + force functions
    for thunk in &module.thunks {
        emit_thunk_cell(thunk, &mut out, &ctx)?;
    }
    for thunk in &module.thunks {
        emit_thunk_force(thunk, &module.thunks, &module.fns, &module.types, &mut out, &mut ctx)?;
    }
    // Function definitions
    for func in &module.fns {
        emit_fn(func, &module.thunks, &module.fns, &module.types, &mut out, &mut ctx)?;
    }
    Ok(out)
}

struct LlvmCtx {
    reg_types: std::collections::HashMap<usize, IrType>,
    enum_names: std::collections::HashSet<String>,
    label_counter: usize,
}

impl LlvmCtx {
    fn new() -> Self {
        LlvmCtx {
            reg_types: std::collections::HashMap::new(),
            enum_names: std::collections::HashSet::new(),
            label_counter: 0,
        }
    }
    fn set_reg(&mut self, r: usize, ty: IrType) { self.reg_types.insert(r, ty); }
    fn reg_ty(&self, r: &usize) -> &IrType { self.reg_types.get(r).unwrap_or(&IrType::Int) }
    fn reg_llvm_ty(&self, r: &usize) -> String { llvm_type_for(self.reg_ty(r), &self.enum_names) }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let l = format!("{}{}", prefix, self.label_counter);
        self.label_counter += 1;
        l
    }
}

fn ir_type_to_llvm(ty: &IrType) -> String {
    match ty {
        IrType::Int => "i64".into(),
        IrType::Bool => "i1".into(),
        IrType::Char => "i64".into(),
        IrType::Unit => "void".into(),
        IrType::Struct(name) => format!("%struct.{}", name),
        IrType::Enum(name) => format!("%enum.{}", name),
        IrType::Fun(_, ret) => ir_type_to_llvm(ret),
        IrType::Tuple(_) => "i64".into(),
        IrType::Array(t, n) => format!("[{} x {}]", n, ir_type_to_llvm(t)),
        IrType::ThunkRef(_) => "ptr".into(),
    }
}

fn llvm_type_for(ty: &IrType, enum_names: &std::collections::HashSet<String>) -> String {
    match ty {
        IrType::Struct(name) if enum_names.contains(name) => format!("%enum.{}", name),
        IrType::Struct(name) => format!("%struct.{}", name),
        _ => ir_type_to_llvm(ty),
    }
}

fn emit_type_defs(module: &Module, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    // Collect enum names for type resolution (Struct→Enum)
    for e in &module.types.enums { ctx.enum_names.insert(e.name.clone()); }
    // Two-pass: first collect concrete (non-generic, non-recursive) type names
    let is_generic = |name: &str, fields: &[(String, IrType)]| -> bool {
        fields.iter().any(|(_, t)| {
            matches!(t, IrType::Struct(n) if n.len() == 1 && n.chars().next().map_or(false, |c| c.is_ascii_uppercase()))
            || matches!(t, IrType::Enum(n) | IrType::Struct(n) if n == name)
        })
    };
    let mut concrete_s: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut concrete_e: std::collections::HashSet<String> = std::collections::HashSet::new();
    for s in &module.types.structs { if !is_generic(&s.name, &s.fields) { concrete_s.insert(s.name.clone()); } }
    for e in &module.types.enums {
        let all_fields: Vec<(String, IrType)> = e.variants.iter()
            .flat_map(|v| v.fields.iter().map(|(n, t)| (n.clone(), t.clone()))).collect();
        if !is_generic(&e.name, &all_fields) { concrete_e.insert(e.name.clone()); }
    }
    // Emit: concrete definitions for non-generic; opaque for generic without concrete fallback
    let mut emitted_types: std::collections::HashSet<String> = std::collections::HashSet::new();
    for s in &module.types.structs {
        if is_generic(&s.name, &s.fields) {
            if !concrete_s.contains(&s.name) && !emitted_types.contains(&s.name) {
                writeln!(out, "%struct.{} = type opaque ; generic", s.name).ok();
                emitted_types.insert(s.name.clone());
            }
            continue;
        }
        let fields: Vec<String> = s.fields.iter().map(|(_, t)| ir_type_to_llvm(t)).collect();
        writeln!(out, "%struct.{} = type {{ {} }}", s.name, fields.join(", ")).ok();
        emitted_types.insert(s.name.clone());
    }
    for e in &module.types.enums {
        let all_fields: Vec<(String, IrType)> = e.variants.iter()
            .flat_map(|v| v.fields.iter().map(|(n, t)| (n.clone(), t.clone()))).collect();
        if is_generic(&e.name, &all_fields) {
            if !concrete_e.contains(&e.name) && !emitted_types.contains(&e.name) {
                writeln!(out, "%enum.{} = type opaque ; generic/recursive", e.name).ok();
                emitted_types.insert(e.name.clone());
            }
            continue;
        }
        let max_payload = e.variants.iter()
            .map(|v| v.fields.iter().map(|(_, t)| ir_type_to_llvm(t)).collect::<Vec<_>>().join(", "))
            .max_by_key(|s| s.len())
            .unwrap_or_default();
        let payload_type = if max_payload.is_empty() { "i64".into() } else { format!("i64") };
        writeln!(out, "%enum.{} = type {{ i64, {} }}", e.name, payload_type).ok();
    }
    Ok(())
}

fn emit_externals(out: &mut String) {
    writeln!(out, "@.fmt_int = private constant [4 x i8] c\"%ld\\00\"", ).ok();
    writeln!(out, "@.fmt_char = private constant [3 x i8] c\"%c\\00\"", ).ok();
    writeln!(out, "declare i32 @printf(ptr, ...)").ok();
    writeln!(out, "declare i32 @scanf(ptr, ...)").ok();
    writeln!(out, "declare i32 @putchar(i32)").ok();
    writeln!(out, "declare i32 @getchar()").ok();
    writeln!(out, "declare ptr @malloc(i64)").ok();
    writeln!(out, "declare void @free(ptr)").ok();
    writeln!(out, "declare void @llvm.trap()").ok();
    writeln!(out).ok();
}

fn emit_thunk_cell(thunk: &Thunk, out: &mut String, _ctx: &LlvmCtx) -> Result<(), String> {
    let val_type = ir_type_to_llvm(&thunk.result_type);
    writeln!(out, "%thunk.{} = type {{ i64, {} }}", thunk.name, val_type).ok();
    writeln!(out, "@{}.cell = global %thunk.{} zeroinitializer", thunk.name, thunk.name).ok();
    writeln!(out).ok();
    Ok(())
}

fn emit_thunk_force(thunk: &Thunk, all_thunks: &[Thunk], all_fns: &[Fn], types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    let ret_ty = ir_type_to_llvm(&thunk.result_type);
    writeln!(out, "define {} @force_{}() {{", ret_ty, thunk.name).ok();

    writeln!(out, "entry:").ok();
    writeln!(out, "  %state.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 0", thunk.name, thunk.name).ok();
    writeln!(out, "  %state = load i64, ptr %state.ptr").ok();
    writeln!(out, "  %is_susp = icmp eq i64 %state, 0").ok();
    writeln!(out, "  br i1 %is_susp, label %eval, label %check_eval").ok();

    writeln!(out, "check_eval:").ok();
    writeln!(out, "  %is_eval = icmp eq i64 %state, 1").ok();
    writeln!(out, "  br i1 %is_eval, label %cycle, label %cached").ok();

    writeln!(out, "eval:").ok();
    writeln!(out, "  store i64 1, ptr %state.ptr").ok();

    for instr in &thunk.blocks.first().map(|b| b.instrs.clone()).unwrap_or_default() {
        emit_llvm_instr(&instr, all_thunks, all_fns, types, out, ctx)?;
    }

    let result_reg = thunk.blocks.first()
        .and_then(|b| b.instrs.last())
        .map(|i| match i { Instr::Lit(r, _) | Instr::Add(r, ..) | Instr::Sub(r, ..) | Instr::Mul(r, ..) | Instr::Div(r, ..) | Instr::Rem(r, ..) | Instr::Call(r, ..) | Instr::Force(r, ..) => *r, _ => 0 })
        .unwrap_or(0);

    writeln!(out, "  %val.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", thunk.name, thunk.name).ok();
    writeln!(out, "  store {} %r{}, ptr %val.ptr", ret_ty, result_reg).ok();
    writeln!(out, "  store i64 2, ptr %state.ptr").ok();
    writeln!(out, "  ret {} %r{}", ret_ty, result_reg).ok();

    writeln!(out, "cycle:").ok();
    writeln!(out, "  call void @llvm.trap()").ok();
    writeln!(out, "  unreachable").ok();

    writeln!(out, "cached:").ok();
    writeln!(out, "  %val.ptr2 = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", thunk.name, thunk.name).ok();
    writeln!(out, "  %cached = load {}, ptr %val.ptr2", ret_ty).ok();
    writeln!(out, "  ret {} %cached", ret_ty).ok();

    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_fn(func: &Fn, all_thunks: &[Thunk], all_fns: &[Fn], _types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    ctx.reg_types.clear();
    // Skip stdlib functions that use generic/opaque aggregate types
    if func.name == "list_sum" || func.name == "list_length" || func.name == "println" {
        return Ok(());
    }
    for (r, t) in &func.params { ctx.set_reg(*r, t.clone()); }
    let ret_ty = if func.name == "main" { "i32".to_string() } else { llvm_type_for(&func.return_type, &ctx.enum_names) };
    let params: Vec<String> = func.params.iter()
        .map(|(r, _)| format!("i64 %r{}", r))
        .collect();
    writeln!(out, "define {} @{}({}) {{", ret_ty, func.name, params.join(", ")).ok();

    for block in &func.blocks {
        writeln!(out, "{}:", block.label).ok();
        for instr in &block.instrs {
            emit_llvm_instr(instr, all_thunks, all_fns, _types, out, ctx)?;
        }
        let term_ret_ty = if func.name == "main" { IrType::Int } else { func.return_type.clone() };
        emit_terminator(&block.terminator, &term_ret_ty, out, func.name == "main")?;
    }
    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_llvm_instr(instr: &Instr, _thunks: &[Thunk], fns: &[Fn], types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    match instr {
        Instr::Lit(r, v) => {
            let ty = match v { LitValue::Int(_) => IrType::Int, LitValue::Bool(_) => IrType::Bool, LitValue::Char(_) => IrType::Char };
            ctx.set_reg(*r, ty);
            match v {
                LitValue::Int(n) => writeln!(out, "  %r{} = add i64 0, {}", r, n).ok(),
                LitValue::Bool(b) => writeln!(out, "  %r{} = add i1 0, {}", r, if *b { "true" } else { "false" }).ok(),
                LitValue::Char(c) => writeln!(out, "  %r{} = add i64 0, {}", r, *c as u32 as i64).ok(),
            };
        }
        Instr::Add(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = add i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Sub(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = sub i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Mul(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = mul i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Div(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = sdiv i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Rem(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = srem i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Lt(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp slt i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Gt(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp sgt i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Le(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp sle i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Ge(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp sge i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Eq(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp eq i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Ne(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = icmp ne i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::And(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = and i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Or(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = or i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Not(r, a) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = xor i1 %r{}, true", r, a).ok(); }
        Instr::Call(r, target, args, ..) => {
            match target {
                CallTarget::Static(name) => {
                    let callee = fns.iter().find(|f| &f.name == name).ok_or("fn not found")?;
                    ctx.set_reg(*r, callee.return_type.clone());
                    let ret_ty = ir_type_to_llvm(&callee.return_type);
                    let arg_str: Vec<String> = args.iter().enumerate()
                        .map(|(i, reg)| format!("{} %r{}", ctx.reg_llvm_ty(reg), reg))
                        .collect();
                    writeln!(out, "  %r{} = call {} @{}({})", r, ret_ty, name, arg_str.join(", ")).ok();
                }
                CallTarget::Dynamic(_) => { writeln!(out, "  ; dynamic call (not implemented)").ok(); ctx.set_reg(*r, IrType::Int); }
            }
        }
        Instr::Force(r, target) => {
            let name = match target { ForceTarget::Static(n) => n.clone(), ForceTarget::Dynamic(_) => "unknown".into() };
            ctx.set_reg(*r, IrType::Int);
            writeln!(out, "  %r{} = call i64 @force_{}()", r, name).ok();
        }
        Instr::Stdout(r) => { writeln!(out, "  call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 %r{})", r).ok(); }
        Instr::Stdin(r) => { ctx.set_reg(*r, IrType::Int);
            writeln!(out, "  %r{}_ptr = alloca i64", r).ok();
            writeln!(out, "  call i32 (ptr, ...) @scanf(ptr @.fmt_int, ptr %r{}_ptr)", r).ok();
            writeln!(out, "  %r{} = load i64, ptr %r{}_ptr", r, r).ok();
        }
        Instr::Phi(r, pairs) => {
            let p: Vec<String> = pairs.iter().map(|(v, l)| format!("%r{}, %{}", v, l)).collect();
            ctx.set_reg(*r, ctx.reg_ty(&pairs[0].0).clone());
            writeln!(out, "  %r{} = phi i64 [{}]", r, p.join("], [")).ok();
        }
        Instr::StructCons(r, name, fields) => {
            ctx.set_reg(*r, IrType::Struct(name.clone()));
            if fields.is_empty() {
                writeln!(out, "  %r{} = add i64 0, 0", r).ok();
            } else {
                let st_ty = format!("%struct.{}", name);
                let f: Vec<String> = fields.iter().map(|f| format!("i64 %r{}", f)).collect();
                writeln!(out, "  %r{}_0 = insertvalue {} undef, {}, 0", r, st_ty, f.first().unwrap_or(&"i64 0".into())).ok();
                let mut prev = format!("%r{}_0", r);
                for (i, fv) in fields.iter().skip(1).enumerate() {
                    let idx = i + 1;
                    let next = format!("%r{}_{}", r, idx);
                    writeln!(out, "  {} = insertvalue {} {}, i64 %r{}, {}", next, st_ty, prev, fv, idx).ok();
                    prev = next;
                }
                // Ptr-to-int to fit struct in i64 register space
                writeln!(out, "  %r{}_ptr = alloca {}", r, st_ty).ok();
                writeln!(out, "  store {} {}, ptr %r{}_ptr", st_ty, prev, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr %r{}_ptr to i64", r, r).ok();
            }
        }
        Instr::EnumCons(r, enum_name, variant_name, fields) => {
            ctx.set_reg(*r, IrType::Enum(enum_name.clone()));
            let en_ty = format!("%enum.{}", enum_name);
            let tag = types.enums.iter()
                .find(|e| e.name == *enum_name)
                .and_then(|e| e.variants.iter().position(|v| v.name == *variant_name))
                .unwrap_or(0);
            writeln!(out, "  %r{}_tag = add i64 0, {}", r, tag).ok();
            writeln!(out, "  %r{}_0 = insertvalue {} undef, i64 %r{}_tag, 0", r, en_ty, r).ok();
            let mut prev = format!("%r{}_0", r);
            for (i, fv) in fields.iter().enumerate() {
                let next = format!("%r{}_{}", r, i + 1);
                writeln!(out, "  {} = insertvalue {} {}, i64 %r{}, {}", next, en_ty, prev, fv, i + 1).ok();
                prev = next;
            }
            writeln!(out, "  %r{}_ptr = alloca {}", r, en_ty).ok();
            writeln!(out, "  store {} {}, ptr %r{}_ptr", en_ty, prev, r).ok();
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_ptr to i64", r, r).ok();
        }
        Instr::EnumDisc(r, reg) => {
            ctx.set_reg(*r, IrType::Int);
            match ctx.reg_ty(reg) {
                IrType::Enum(name) | IrType::Struct(name) => {
                    let is_opaque = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if is_opaque { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
                    else {
                        let base_ty = ctx.reg_llvm_ty(reg);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, reg).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, 0", r, base_ty, r).ok();
                    }
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
            }
        }
        Instr::EnumProj(r, _enum_name, _variant, idx, reg) => {
            ctx.set_reg(*r, IrType::Int);
            match ctx.reg_ty(reg) {
                IrType::Enum(name) | IrType::Struct(name) => {
                    let is_opaque = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if is_opaque { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
                    else {
                        let base_ty = ctx.reg_llvm_ty(reg);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, reg).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, base_ty, r, idx + 1).ok();
                    }
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
            }
        }
        Instr::Field(r, base, idx, ..) => {
            ctx.set_reg(*r, IrType::Int);
            match ctx.reg_ty(base) {
                IrType::Struct(name) | IrType::Enum(name) => {
                    let is_generic = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if !is_generic {
                        let st_ty = if matches!(ctx.reg_ty(base), IrType::Enum(_)) { format!("%enum.{}", name) } else { format!("%struct.{}", name) };
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, st_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, st_ty, r, idx).ok();
                    } else {
                        writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok();
                    }
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok(); }
            }
        }
        Instr::StructUpdate(r, base, fidx, val, ..) => {
            let base_ty = ctx.reg_llvm_ty(base);
            ctx.set_reg(*r, ctx.reg_ty(base).clone());
            writeln!(out, "  %r{} = insertvalue {} %r{}, i64 %r{}, {}", r, base_ty, base, val, fidx).ok();
        }
        Instr::ArrayLit(r, _ty, elems) => {
            let n = elems.len();
            writeln!(out, "  %r{}_arr = alloca [{} x i64]", r, n).ok();
            for (i, e) in elems.iter().enumerate() {
                writeln!(out, "  %r{}_ptr{} = getelementptr [{} x i64], ptr %r{}_arr, i32 0, i32 {}", r, i, n, r, i).ok();
                writeln!(out, "  store i64 %r{}, ptr %r{}_ptr{}", e, r, i).ok();
            }
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_arr to i64", r, r).ok();
        }
        Instr::ArrayFill(r, _ty, val, n) => {
            writeln!(out, "  %r{}_arr = alloca [{} x i64]", r, n).ok();
            for i in 0..*n {
                writeln!(out, "  %r{}_ptr{} = getelementptr [{} x i64], ptr %r{}_arr, i32 0, i32 {}", r, i, n, r, i).ok();
                writeln!(out, "  store i64 %r{}, ptr %r{}_ptr{}", val, r, i).ok();
            }
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_arr to i64", r, r).ok();
        }
        Instr::ArrayAccess(r, arr, idx) => {
            writeln!(out, "  %r{}_p = inttoptr i64 %r{} to ptr", r, arr).ok();
            writeln!(out, "  %r{}_ep = getelementptr i64, ptr %r{}_p, i64 %r{}", r, r, idx).ok();
            writeln!(out, "  %r{} = load i64, ptr %r{}_ep", r, r).ok();
        }
        Instr::ArrayUpdate(r, arr, idx, val) => {
            writeln!(out, "  %r{}_p = inttoptr i64 %r{} to ptr", r, arr).ok();
            writeln!(out, "  %r{}_ep = getelementptr i64, ptr %r{}_p, i64 %r{}", r, r, idx).ok();
            writeln!(out, "  store i64 %r{}, ptr %r{}_ep", val, r).ok();
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, arr).ok();
        }
        Instr::TupleLit(r, _ty, elems) => {
            writeln!(out, "  %r{} = add i64 0, 0", r).ok();
            for (i, e) in elems.iter().enumerate() {
                writeln!(out, "  %r{} = insertvalue {{ {} }} %r{}, i64 %r{}, {}", r,
                    (0..elems.len()).map(|_| "i64").collect::<Vec<_>>().join(", "), r, e, i).ok();
            }
        }
        Instr::TupleUpdate(r, tup, idx, val) => {
            writeln!(out, "  %r{} = insertvalue i64 %r{}, i64 %r{}, {}", r, tup, val, idx).ok();
        }
        Instr::Fetch(r, base, path) => {
            writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
            let mut prev = format!("%r{}_ptr", r);
            for (i, accessor) in path.iter().enumerate() {
                match accessor {
                    Accessor::Field(name) => {
                        let next = format!("%r{}_f{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i32 {}", next, prev, name.len()).ok();
                        prev = next;
                    }
                    Accessor::Index(reg) => {
                        let next = format!("%r{}_i{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i64 %r{}", next, prev, reg).ok();
                        prev = next;
                    }
                    Accessor::TupleIndex(idx) => {
                        writeln!(out, "  %r{} = extractvalue i64 %r{}, {}", r, base, idx).ok();
                        return Ok(());
                    }
                }
            }
            writeln!(out, "  %r{} = load i64, ptr {}", r, prev).ok();
        }
        Instr::Place(r, base, path, val) => {
            let mut prev = format!("%r{}_p", r);
            writeln!(out, "  {} = inttoptr i64 %r{} to ptr", prev, base).ok();
            for (i, accessor) in path.iter().enumerate() {
                match accessor {
                    Accessor::Field(name) => {
                        let next = format!("%r{}_f{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i32 {}", next, prev, name.len()).ok();
                        prev = next;
                    }
                    Accessor::Index(reg) => {
                        let next = format!("%r{}_i{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i64 %r{}", next, prev, reg).ok();
                        prev = next;
                    }
                    Accessor::TupleIndex(idx) => {
                        writeln!(out, "  %r{} = insertvalue i64 %r{}, i64 %r{}, {}", r, base, val, idx).ok();
                        return Ok(());
                    }
                }
            }
            writeln!(out, "  store i64 %r{}, ptr {}", val, prev).ok();
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok();
        }
        Instr::Lambda(r, fn_name, _captures) => {
            writeln!(out, "  ; lambda {} -> fn @{}, captures not yet lowered", r, fn_name).ok();
            writeln!(out, "  %r{} = add i64 0, 0", r).ok();
        }
        Instr::Move(r, from) => {
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, from).ok();
        }
        _ => { writeln!(out, "  ; unimplemented instruction").ok(); }
    }
    Ok(())
}

fn emit_terminator(t: &Terminator, ret_ty: &IrType, out: &mut String, is_main: bool) -> Result<(), String> {
    match t {
        Terminator::Ret(r) => {
            if is_main {
                writeln!(out, "  ret i32 0").ok();
            } else if *ret_ty == IrType::Unit {
                writeln!(out, "  ret void").ok();
            } else {
                writeln!(out, "  ret {} %r{}", ir_type_to_llvm(ret_ty), r).ok();
            }
        }
        Terminator::Br(cond, t_label, f_label) => {
            writeln!(out, "  br i1 %r{}, label %{}, label %{}", cond, t_label, f_label).ok();
        }
        Terminator::Jmp(label) => {
            writeln!(out, "  br label %{}", label).ok();
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_simple_module() {
        let mut module = Module::new();
        let mut f = Fn::new("main".into(), vec![], IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(42)));
        block.terminator = Terminator::Ret(0);
        f.blocks.push(block);
        module.fns.push(f);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("define i32 @main"));
        assert!(llvm.contains("ret i32 0"));
    }

    #[test]
    fn generate_with_thunk() {
        let mut module = Module::new();
        let mut t = Thunk::new("x".into(), IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(2026)));
        block.terminator = Terminator::Ret(0);
        t.blocks.push(block);
        module.thunks.push(t);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("@x.cell"));
        assert!(llvm.contains("define i64 @force_x"));
    }
}
