use crate::ir::block::BasicBlock;
use crate::ir::func::Fn;
use crate::ir::instr::*;
use crate::ir::module::Module;
use crate::ir::thunk::Thunk;
use crate::ir::types::*;
use std::fmt::Write;

pub fn generate(module: &Module) -> Result<String, String> {
    let mut out = String::new();
    let mut ctx = LlvmCtx::new();

    writeln!(out, "; Dew IR → LLVM IR translation").ok();
    writeln!(out, "; Generated by dew compiler").ok();
    writeln!(out).ok();

    // Type definitions
    emit_type_defs(module, &mut out, &mut ctx)?;
    // External declarations
    emit_externals(&mut out);
    // Thunk cells + force functions (deduplicated)
    let mut emitted_thunks: std::collections::HashSet<String> = std::collections::HashSet::new();
    for thunk in &module.thunks {
        let name = thunk.name.clone();
        if emitted_thunks.contains(&name) { continue; }
        emitted_thunks.insert(name);
        emit_thunk_cell(thunk, &mut out, &ctx)?;
        emit_thunk_force(thunk, &module.thunks, &module.fns, &module.types, &mut out, &mut ctx)?;
    }
    // Function definitions (deduplicated, last definition wins for overrides)
    let mut emitted_fns: std::collections::HashSet<String> = std::collections::HashSet::new();
    for func in &module.fns {
        let name = func.name.clone();
        if emitted_fns.contains(&name) { continue; }
        emitted_fns.insert(name);
        emit_fn(func, &module.thunks, &module.fns, &module.types, &mut out, &mut ctx)?;
    }
    Ok(out)
}

struct LlvmCtx {
    reg_types: std::collections::HashMap<usize, IrType>,
    enum_names: std::collections::HashSet<String>,
    recursive_enums: std::collections::HashSet<String>,
    label_counter: usize,
    arena_used: usize,
    closure_ids: std::collections::HashMap<String, usize>,
    next_closure_id: usize,
    closure_env: std::collections::HashMap<usize, ClosureEnv>,
}

#[derive(Clone)]
struct ClosureEnv {
    fn_name: String,
    capture_count: usize,
    cap_ptr_ssa: String,
}

impl LlvmCtx {
    fn new() -> Self {
        LlvmCtx {
            reg_types: std::collections::HashMap::new(),
            enum_names: std::collections::HashSet::new(),
            recursive_enums: std::collections::HashSet::new(),
            label_counter: 0,
            arena_used: 0,
            closure_ids: std::collections::HashMap::new(),
            next_closure_id: 0,
            closure_env: std::collections::HashMap::new(),
        }
    }
    fn set_reg(&mut self, r: usize, ty: IrType) { self.reg_types.insert(r, ty); }
    fn reg_ty(&self, r: &usize) -> &IrType { self.reg_types.get(r).unwrap_or(&IrType::Int) }
    fn reg_llvm_ty(&self, r: &usize) -> String { llvm_type_for(self.reg_ty(r), &self.enum_names) }

    fn is_recursive_enum(&self, name: &str) -> bool { self.recursive_enums.contains(name) }

    fn register_closure(&mut self, fn_name: &str, _capture_count: usize) -> usize {
        if let Some(&id) = self.closure_ids.get(fn_name) { return id; }
        let id = self.next_closure_id;
        self.next_closure_id += 1;
        self.closure_ids.insert(fn_name.to_string(), id);
        id
    }

    fn arena_alloc(&mut self, size_bytes: usize, out: &mut String) -> String {
        let aligned = (size_bytes + 7) & !7;
        let a = self.arena_used;
        self.arena_used += 1;
        writeln!(out, "  %a_off{} = load i64, ptr @arena.off", a).ok();
        writeln!(out, "  %a_new{} = add i64 %a_off{}, {}", a, a, aligned).ok();
        writeln!(out, "  store i64 %a_new{}, ptr @arena.off", a).ok();
        writeln!(out, "  %a_ptr{} = getelementptr [65536 x i8], ptr @arena.buf, i32 0, i64 %a_off{}", a, a).ok();
        format!("%a_ptr{}", a)
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let l = format!("{}{}", prefix, self.label_counter);
        self.label_counter += 1;
        l
    }
}

/// Emit a register as i64 for struct/enum storage, zexting Bool → i64.
fn as_i64(r: usize, reg: usize, out: &mut String, ctx: &LlvmCtx) -> String {
    match ctx.reg_ty(&reg) {
        IrType::Bool => { writeln!(out, "  %r{}_z = zext i1 %r{} to i64", r, reg).ok(); format!("%r{}_z", r) }
        IrType::Char => { writeln!(out, "  %r{}_z = zext i32 %r{} to i64", r, reg).ok(); format!("%r{}_z", r) }
        _ => format!("%r{}", reg),
    }
}

/// Convert a register to i64 with a unique temp name, used for comparison operands.
fn as_i64_tmp(r: usize, tag: &str, reg: usize, out: &mut String, ctx: &LlvmCtx) -> String {
    match ctx.reg_ty(&reg) {
        IrType::Bool => { writeln!(out, "  %r{}_{} = zext i1 %r{} to i64", r, tag, reg).ok(); format!("%r{}_{}", r, tag) }
        IrType::Char => { writeln!(out, "  %r{}_{} = zext i32 %r{} to i64", r, tag, reg).ok(); format!("%r{}_{}", r, tag) }
        _ => format!("%r{}", reg),
    }
}

fn ir_type_to_llvm(ty: &IrType) -> String {
    match ty {
        IrType::Undefined => "i64".into(),
        IrType::Int => "i64".into(),
        IrType::Bool => "i1".into(),
        IrType::Char => "i32".into(),
        IrType::Unit => "void".into(),
        IrType::Struct(name) if name == "%tuple" => "i64".into(), // tuple placeholder — use i64
        IrType::Struct(name) => format!("%struct.{}", name),
        IrType::Enum(name) => format!("%enum.{}", name),
        IrType::Fun(_, ret) => ir_type_to_llvm(ret),
        IrType::Tuple(elements) => format!("{{ {} }}", (0..elements.len()).map(|_| "i64").collect::<Vec<_>>().join(", ")),
        IrType::Array(t, n) => format!("[{} x {}]", n, ir_type_to_llvm(t)),
        IrType::ThunkRef(_) => "ptr".into(),
    }
}

fn llvm_type_for(ty: &IrType, enum_names: &std::collections::HashSet<String>) -> String {
    match ty {
        IrType::Struct(name) if name == "%tuple" => "i64".into(),
        IrType::Struct(name) if enum_names.contains(name) => format!("%enum.{}", name),
        IrType::Struct(name) => format!("%struct.{}", name),
        IrType::Tuple(elements) => format!("{{ {} }}", (0..elements.len()).map(|_| "i64").collect::<Vec<_>>().join(", ")),
        _ => ir_type_to_llvm(ty),
    }
}

/// LLVM type for a register used in function boundaries (params, call args).
/// Aggregates → i64; primitive types use their natural LLVM type.
fn llvm_boundary_type(ty: &IrType) -> String {
    match ty {
        IrType::Struct(_) | IrType::Enum(_) | IrType::Tuple(_) | IrType::Array(_, _) => "i64".into(),
        _ => ir_type_to_llvm(ty),
    }
}

fn emit_type_defs(module: &Module, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    // Collect enum names for type resolution (Struct→Enum)
    for e in &module.types.enums { ctx.enum_names.insert(e.name.clone()); }
    // Detect recursive enums (self-referencing variant fields)
    for e in &module.types.enums {
        let is_recursive = e.variants.iter().any(|v|
            v.fields.iter().any(|(_, t)| matches!(t, IrType::Enum(n) | IrType::Struct(n) if n == &e.name))
        );
        if is_recursive { ctx.recursive_enums.insert(e.name.clone()); }
    }
    // Two-pass: first collect concrete (non-generic, non-recursive) type names
    let is_generic = |name: &str, fields: &[(String, IrType)]| -> bool {
        fields.iter().any(|(_, t)| {
            matches!(t, IrType::Struct(n) if n.len() == 1 && n.chars().next().map_or(false, |c| c.is_ascii_uppercase()))
            || matches!(t, IrType::Enum(n) | IrType::Struct(n) if n == name)
        })
    };
    let mut concrete_s: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut concrete_e: std::collections::HashSet<String> = std::collections::HashSet::new();
    for s in &module.types.structs { if !is_generic(&s.name, &s.fields) { concrete_s.insert(s.name.clone()); } }
    for e in &module.types.enums {
        let all_fields: Vec<(String, IrType)> = e.variants.iter()
            .flat_map(|v| v.fields.iter().map(|(n, t)| (n.clone(), t.clone()))).collect();
        if !is_generic(&e.name, &all_fields) { concrete_e.insert(e.name.clone()); }
    }
    // Emit: concrete for non-generic; arena-based {i64,ptr} for recursive
    let mut emitted_types: std::collections::HashSet<String> = std::collections::HashSet::new();
    for s in &module.types.structs {
        if is_generic(&s.name, &s.fields) {
            if !concrete_s.contains(&s.name) && !emitted_types.contains(&s.name) {
                // Generic with no concrete instantiation: emit with i64 fields (register model)
                let fields: Vec<String> = s.fields.iter().map(|_| "i64".into()).collect();
                writeln!(out, "%struct.{} = type {{ {} }}", s.name, fields.join(", ")).ok();
                emitted_types.insert(s.name.clone());
            }
            continue;
        }
        let fields: Vec<String> = s.fields.iter().map(|_| "i64".into()).collect();
        writeln!(out, "%struct.{} = type {{ {} }}", s.name, fields.join(", ")).ok();
        emitted_types.insert(s.name.clone());
    }
    for e in &module.types.enums {
        if ctx.is_recursive_enum(&e.name) {
            if !emitted_types.contains(&e.name) {
                writeln!(out, "%enum.{} = type {{ i64, ptr }}", e.name).ok();
                emitted_types.insert(e.name.clone());
            }
            continue;
        }
        let all_fields: Vec<(String, IrType)> = e.variants.iter()
            .flat_map(|v| v.fields.iter().map(|(n, t)| (n.clone(), t.clone()))).collect();
        if is_generic(&e.name, &all_fields) {
            if !concrete_e.contains(&e.name) && !emitted_types.contains(&e.name) {
                writeln!(out, "%enum.{} = type {{ i64, i64 }}", e.name).ok();
                emitted_types.insert(e.name.clone());
            }
            continue;
        }
        let max_payload = e.variants.iter()
            .map(|v| v.fields.len())
            .max().unwrap_or(0);
        let payload_type = if max_payload <= 1 { "i64".into() } else { format!("{{ {} }}", (0..max_payload).map(|_| "i64").collect::<Vec<_>>().join(", ")) };
        writeln!(out, "%enum.{} = type {{ i64, {} }}", e.name, payload_type).ok();
        emitted_types.insert(e.name.clone());
    }
    Ok(())
}

fn infer_thunk_result_type(thunk: &Thunk) -> IrType {
    if thunk.result_type != IrType::Int { return thunk.result_type.clone(); }
    let ret_reg = thunk.blocks.first()
        .and_then(|b| match &b.terminator { Terminator::Ret(r) => Some(r), _ => None });
    if let Some(&reg) = ret_reg {
        for instr in thunk.blocks.first().map(|b| &b.instrs).unwrap_or(&vec![]) {
            match instr {
                Instr::EnumCons(dst, name, _, _) if *dst == reg => return IrType::Enum(name.clone()),
                Instr::StructCons(dst, ty, _) if *dst == reg => return ty.clone(),
                _ => {}
            }
        }
    }
    IrType::Int
}

fn emit_externals(out: &mut String) {
    writeln!(out, "@arena.buf = global [65536 x i8] zeroinitializer").ok();
    writeln!(out, "@arena.off = global i64 0").ok();
    writeln!(out, "@.fmt_int = private constant [4 x i8] c\"%ld\\00\"", ).ok();
    writeln!(out, "@.fmt_char = private constant [3 x i8] c\"%c\\00\"", ).ok();
    writeln!(out, "@.str_true = private constant [5 x i8] c\"true\\00\"").ok();
    writeln!(out, "@.str_false = private constant [6 x i8] c\"false\\00\"").ok();
    writeln!(out, "declare i32 @printf(ptr, ...)").ok();
    writeln!(out, "declare i32 @scanf(ptr, ...)").ok();
    writeln!(out, "declare i32 @putchar(i32)").ok();
    writeln!(out, "declare i32 @getchar()").ok();
    writeln!(out, "declare ptr @malloc(i64)").ok();
    writeln!(out, "declare void @free(ptr)").ok();
    writeln!(out, "declare void @llvm.trap()").ok();
    writeln!(out).ok();
}

fn llvm_safe_name(name: &str) -> String {
    name.replace('@', "_at_").replace('%', "_pct_")
}

fn emit_thunk_cell(thunk: &Thunk, out: &mut String, _ctx: &LlvmCtx) -> Result<(), String> {
    let val_type = match &thunk.result_type {
        IrType::Struct(_) | IrType::Enum(_) | IrType::Tuple(_) => "i64".into(),
        _ => llvm_boundary_type(&thunk.result_type),
    };
    let safe_name = llvm_safe_name(&thunk.name);
    writeln!(out, "%thunk.{} = type {{ i64, {} }}", safe_name, val_type).ok();
    writeln!(out, "@{}.cell = global %thunk.{} zeroinitializer", safe_name, safe_name).ok();
    writeln!(out).ok();
    Ok(())
}

fn emit_thunk_force(thunk: &Thunk, all_thunks: &[Thunk], all_fns: &[Fn], types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    ctx.reg_types.clear();
    ctx.closure_env.clear();
    let ret_llvm = match &thunk.result_type {
        IrType::Struct(_) | IrType::Enum(_) | IrType::Tuple(_) => "i64".into(),
        _ => llvm_boundary_type(&thunk.result_type),
    };
    let safe_name = llvm_safe_name(&thunk.name);
    writeln!(out, "define {} @force_{}() {{", ret_llvm, safe_name).ok();

    writeln!(out, "entry:").ok();
    writeln!(out, "  %state.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 0", safe_name, safe_name).ok();
    writeln!(out, "  %state = load i64, ptr %state.ptr").ok();
    writeln!(out, "  %is_susp = icmp eq i64 %state, 0").ok();
    writeln!(out, "  br i1 %is_susp, label %eval, label %check_eval").ok();

    writeln!(out, "check_eval:").ok();
    writeln!(out, "  %is_eval = icmp eq i64 %state, 1").ok();
    writeln!(out, "  br i1 %is_eval, label %cycle, label %cached").ok();

    writeln!(out, "eval:").ok();
    writeln!(out, "  store i64 1, ptr %state.ptr").ok();

    // Process first block's instructions directly into eval,
    // then follow its terminator to other blocks.
    let first = thunk.blocks.first().ok_or("thunk has no blocks")?;
    for instr in &first.instrs {
        emit_llvm_instr(instr, all_thunks, all_fns, types, out, ctx)?;
    }
    // Emit first block's terminator — for Ret, store+return; for Br/Jmp, follow
    emit_thunk_terminator(&first.terminator, &thunk.result_type, &safe_name, &ret_llvm, all_thunks, all_fns, types, out, ctx)?;

    // Process remaining blocks
    for block in thunk.blocks.iter().skip(1) {
        writeln!(out, "{}:", block.label).ok();
        for instr in &block.instrs {
            emit_llvm_instr(instr, all_thunks, all_fns, types, out, ctx)?;
        }
        emit_thunk_terminator(&block.terminator, &thunk.result_type, &safe_name, &ret_llvm, all_thunks, all_fns, types, out, ctx)?;
    }

    writeln!(out, "cycle:").ok();
    writeln!(out, "  call void @llvm.trap()").ok();
    writeln!(out, "  unreachable").ok();

    writeln!(out, "cached:").ok();
    writeln!(out, "  %val.ptr2 = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", safe_name, safe_name).ok();
    writeln!(out, "  %val_cached = load {}, ptr %val.ptr2", ret_llvm).ok();
    writeln!(out, "  ret {} %val_cached", ret_llvm).ok();

    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_thunk_terminator(t: &Terminator, ret_ty: &IrType, thunk_name: &str, ret_llvm: &str, all_thunks: &[Thunk], all_fns: &[Fn], types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    match t {
        Terminator::Ret(r) => {
            // Store result in cell before returning
            writeln!(out, "  %val.ptr = getelementptr %thunk.{}, ptr @{}.cell, i32 0, i32 1", thunk_name, thunk_name).ok();
            writeln!(out, "  store {} %r{}, ptr %val.ptr", ret_llvm, r).ok();
            writeln!(out, "  store i64 2, ptr %state.ptr").ok();
            let val = match (ret_ty, ctx.reg_ty(r)) {
                (IrType::Int, IrType::Char) => { writeln!(out, "  %r{}_ret = zext i32 %r{} to i64", r, r).ok(); format!("%r{}_ret", r) }
                _ => format!("%r{}", r),
            };
            writeln!(out, "  ret {} {}", ret_llvm, val).ok();
        }
        Terminator::Br(cond, t_label, f_label) => {
            writeln!(out, "  br i1 %r{}, label %{}, label %{}", cond, t_label, f_label).ok();
        }
        Terminator::Jmp(label) => {
            writeln!(out, "  br label %{}", label).ok();
        }
    }
    Ok(())
}

fn emit_fn(func: &Fn, all_thunks: &[Thunk], all_fns: &[Fn], _types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    ctx.reg_types.clear();
    ctx.closure_env.clear();
    for (r, t) in &func.params { ctx.set_reg(*r, t.clone()); }
    let ret_llvm = if func.name == "main" {
        "i32".to_string()
    } else {
        match &func.return_type {
            IrType::Struct(_) | IrType::Enum(_) | IrType::Tuple(_) => "i64".to_string(),
            _ => llvm_boundary_type(&func.return_type),
        }
    };
    let params: Vec<String> = func.params.iter()
        .map(|(r, t)| format!("{} %r{}", llvm_boundary_type(t), r))
        .collect();
    writeln!(out, "define {} @{}({}) {{", ret_llvm, func.name, params.join(", ")).ok();

    for block in &func.blocks {
        writeln!(out, "{}:", block.label).ok();
        for instr in &block.instrs {
            emit_llvm_instr(instr, all_thunks, all_fns, _types, out, ctx)?;
        }
        emit_terminator(&block.terminator, &func.return_type, out, ctx, func.name == "main")?;
    }
    writeln!(out, "}}\n").ok();
    Ok(())
}

fn emit_llvm_instr(instr: &Instr, _thunks: &[Thunk], fns: &[Fn], types: &TypeTable, out: &mut String, ctx: &mut LlvmCtx) -> Result<(), String> {
    match instr {
        Instr::Lit(r, v) => {
            let ty = match v { LitValue::Int(_) => IrType::Int, LitValue::Bool(_) => IrType::Bool, LitValue::Char(_) => IrType::Char };
            ctx.set_reg(*r, ty);
            match v {
                LitValue::Int(n) => writeln!(out, "  %r{} = add i64 0, {}", r, n).ok(),
                LitValue::Bool(b) => writeln!(out, "  %r{} = add i1 0, {}", r, if *b { "true" } else { "false" }).ok(),
                LitValue::Char(c) => writeln!(out, "  %r{} = add i32 0, {}", r, *c as u32 as i32).ok(),
            };
        }
        Instr::Add(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = add i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Sub(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = sub i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Mul(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = mul i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Div(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = sdiv i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Rem(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = srem i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::BitAnd(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = and i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::BitOr(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = or i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::BitXor(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = xor i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Shl(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = shl i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Shr(r, a, b) => { ctx.set_reg(*r, IrType::Int); writeln!(out, "  %r{} = ashr i64 %r{}, %r{}", r, a, b).ok(); }
        Instr::Lt(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "la", *a, out, ctx); let vb = as_i64_tmp(*r, "lb", *b, out, ctx); writeln!(out, "  %r{} = icmp slt i64 {}, {}", r, va, vb).ok(); }
        Instr::Gt(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "ga", *a, out, ctx); let vb = as_i64_tmp(*r, "gb", *b, out, ctx); writeln!(out, "  %r{} = icmp sgt i64 {}, {}", r, va, vb).ok(); }
        Instr::Le(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "lea", *a, out, ctx); let vb = as_i64_tmp(*r, "leb", *b, out, ctx); writeln!(out, "  %r{} = icmp sle i64 {}, {}", r, va, vb).ok(); }
        Instr::Ge(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "gea", *a, out, ctx); let vb = as_i64_tmp(*r, "geb", *b, out, ctx); writeln!(out, "  %r{} = icmp sge i64 {}, {}", r, va, vb).ok(); }
        Instr::Eq(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "eqa", *a, out, ctx); let vb = as_i64_tmp(*r, "eqb", *b, out, ctx); writeln!(out, "  %r{} = icmp eq i64 {}, {}", r, va, vb).ok(); }
        Instr::Ne(r, a, b) => { ctx.set_reg(*r, IrType::Bool); let va = as_i64_tmp(*r, "nea", *a, out, ctx); let vb = as_i64_tmp(*r, "neb", *b, out, ctx); writeln!(out, "  %r{} = icmp ne i64 {}, {}", r, va, vb).ok(); }
        Instr::And(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = and i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Or(r, a, b) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = or i1 %r{}, %r{}", r, a, b).ok(); }
        Instr::Not(r, a) => { ctx.set_reg(*r, IrType::Bool); writeln!(out, "  %r{} = xor i1 %r{}, true", r, a).ok(); }
        Instr::Call(r, target, args, ..) => {
            match target {
                CallTarget::Static(name) => {
                    let callee = fns.iter().find(|f| &f.name == name).ok_or("fn not found")?;
                    ctx.set_reg(*r, callee.return_type.clone());
                    let ret_llvm = llvm_boundary_type(&callee.return_type);
                    let arg_str: Vec<String> = args.iter()
                            .map(|reg| format!("{} %r{}", llvm_boundary_type(ctx.reg_ty(reg)), reg))
                        .collect();
                    writeln!(out, "  %r{} = call {} @{}({})", r, ret_llvm, name, arg_str.join(", ")).ok();
                }
                CallTarget::Dynamic(reg) => {
                    if let Some(env) = ctx.closure_env.get(reg).cloned() {
                        let callee = fns.iter().find(|f| f.name == env.fn_name)
                            .ok_or("closure fn not found")?;
                        ctx.set_reg(*r, callee.return_type.clone());
                        let ret_llvm = llvm_boundary_type(&callee.return_type);
                        let mut call_args: Vec<String> = args.iter()
                        .map(|reg| format!("{} %r{}", llvm_boundary_type(ctx.reg_ty(reg)), reg))
                            .collect();
                        if env.capture_count > 0 {
                            let env_ptr = format!("%r{}_env_ptr", r);
                            writeln!(out, "  {} = inttoptr i64 {} to ptr", env_ptr, env.cap_ptr_ssa).ok();
                            for i in 0..env.capture_count {
                                let gep = format!("%r{}_cap{}_p", r, i);
                                let cap = format!("%r{}_cap{}", r, i);
                                writeln!(out, "  {} = getelementptr i64, ptr {}, i32 {}", gep, env_ptr, i).ok();
                                writeln!(out, "  {} = load i64, ptr {}", cap, gep).ok();
                                call_args.push(format!("i64 {}", cap));
                            }
                        }
                        if ret_llvm == "void" {
                            writeln!(out, "  call void @{}({})", env.fn_name, call_args.join(", ")).ok();
                            writeln!(out, "  %r{} = add i64 0, 0", r).ok();
                        } else {
                            writeln!(out, "  %r{} = call {} @{}({})", r, ret_llvm, env.fn_name, call_args.join(", ")).ok();
                        }
                    } else {
                        writeln!(out, "  ; dynamic call (unknown closure — returns 0)").ok();
                        ctx.set_reg(*r, IrType::Int);
                        writeln!(out, "  %r{} = add i64 0, 0", r).ok();
                    }
                }
            }
        }
        Instr::Force(r, target) => {
            let name = match target { ForceTarget::Static(n) => n.clone(), ForceTarget::Dynamic(_) => "unknown".into() };
            let thunk_ty = _thunks.iter().find(|t| t.name == name)
                .map(|t| infer_thunk_result_type(t))
                .unwrap_or(IrType::Int);
            ctx.set_reg(*r, thunk_ty.clone());
            let force_ret = llvm_boundary_type(&thunk_ty);
            writeln!(out, "  %r{} = call {} @force_{}()", r, force_ret, llvm_safe_name(&name)).ok();
        }
        Instr::Stdout(r) => {
            match ctx.reg_ty(r) {
                IrType::Char => { writeln!(out, "  %r{}_c = call i32 @putchar(i32 %r{})", r, r).ok(); }
                IrType::Bool => {
                    writeln!(out, "  %r{}_z = zext i1 %r{} to i64", r, r).ok();
                    writeln!(out, "  %r{}_c = icmp ne i64 %r{}_z, 0", r, r).ok();
                    writeln!(out, "  br i1 %r{}_c, label %sout_t{}, label %sout_f{}", r, r, r).ok();
                    writeln!(out, "sout_t{}:", r).ok();
                    writeln!(out, "  %r{}_st = call i32 (ptr, ...) @printf(ptr @.str_true)", r).ok();
                    writeln!(out, "  br label %sout_d{}", r).ok();
                    writeln!(out, "sout_f{}:", r).ok();
                    writeln!(out, "  %r{}_sf = call i32 (ptr, ...) @printf(ptr @.str_false)", r).ok();
                    writeln!(out, "  br label %sout_d{}", r).ok();
                    writeln!(out, "sout_d{}:", r).ok();
                }
                _ => { writeln!(out, "  call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 %r{})", r).ok(); }
            }
        }
        Instr::Stdin(r) => { ctx.set_reg(*r, IrType::Int);
            let ptr = ctx.arena_alloc(8, out);
            writeln!(out, "  store i64 0, ptr {}", ptr).ok();
            writeln!(out, "  call i32 (ptr, ...) @scanf(ptr @.fmt_int, ptr {})", ptr).ok();
            writeln!(out, "  %r{} = load i64, ptr {}", r, ptr).ok();
        }
        Instr::Phi(r, pairs) => {
            let p: Vec<String> = pairs.iter().map(|(v, l)| format!("%r{}, %{}", v, l)).collect();
            ctx.set_reg(*r, ctx.reg_ty(&pairs[0].0).clone());
            let phity = llvm_boundary_type(ctx.reg_ty(r));
            writeln!(out, "  %r{} = phi {} [{}]", r, phity, p.join("], [")).ok();
        }
        Instr::StructCons(r, ty, fields) => {
            ctx.set_reg(*r, ty.clone());
            let is_tuple = matches!(ty, IrType::Tuple(_));
            if fields.is_empty() {
                writeln!(out, "  %r{} = add i64 0, 0", r).ok();
            } else if is_tuple {
                // Tuple construction: arena-allocate and store like a struct
                let struct_ty = format!("{{ {} }}", (0..fields.len()).map(|_| "i64").collect::<Vec<_>>().join(", "));
                let first = as_i64(r * 1000, fields[0], out, ctx);
                writeln!(out, "  %r{}_0 = insertvalue {} undef, i64 {}, 0", r, struct_ty, first).ok();
                let mut prev = format!("%r{}_0", r);
                for (i, fv) in fields.iter().skip(1).enumerate() {
                    let idx = i + 1;
                    let next = format!("%r{}_{}", r, idx);
                    let fv_i64 = as_i64(r * 1000 + idx, *fv, out, ctx);
                    writeln!(out, "  {} = insertvalue {} {}, i64 {}, {}", next, struct_ty, prev, fv_i64, idx).ok();
                    prev = next;
                }
                let arena_ptr = ctx.arena_alloc(fields.len() * 8, out);
                writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
                writeln!(out, "  store {} {}, ptr %r{}_cast", struct_ty, prev, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
            } else {
                let struct_name = match ty { IrType::Struct(n) => n.as_str(), _ => "%tuple" };
                let st_ty = format!("%struct.{}", struct_name);
                let first = as_i64(r * 1000, fields[0], out, ctx);
                writeln!(out, "  %r{}_0 = insertvalue {} undef, i64 {}, 0", r, st_ty, first).ok();
                let mut prev = format!("%r{}_0", r);
                for (i, fv) in fields.iter().skip(1).enumerate() {
                    let idx = i + 1;
                    let next = format!("%r{}_{}", r, idx);
                    let fv_i64 = as_i64(r * 1000 + idx, *fv, out, ctx);
                    writeln!(out, "  {} = insertvalue {} {}, i64 {}, {}", next, st_ty, prev, fv_i64, idx).ok();
                    prev = next;
                }
                let size = fields.len() * 8;
                let arena_ptr = ctx.arena_alloc(size, out);
                writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
                writeln!(out, "  store {} {}, ptr %r{}_cast", st_ty, prev, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
            }
        }
        Instr::EnumCons(r, enum_name, variant_name, fields) => {
            ctx.set_reg(*r, IrType::Enum(enum_name.clone()));
            let en_ty = format!("%enum.{}", enum_name);
            let tag = types.enums.iter()
                .find(|e| e.name == *enum_name)
                .and_then(|e| e.variants.iter().position(|v| v.name == *variant_name))
                .unwrap_or(0);
            writeln!(out, "  %r{}_tag = add i64 0, {}", r, tag).ok();
            if ctx.is_recursive_enum(enum_name) {
                let payload_size = fields.len() * 8;
                let arena_ptr = ctx.arena_alloc(payload_size, out);
                for (i, fv) in fields.iter().enumerate() {
                    let fv_i64 = as_i64(r * 1000 + i, *fv, out, ctx);
                    writeln!(out, "  %r{}_f{}_ptr = getelementptr i8, ptr {}, i64 {}", r, i, arena_ptr, i * 8).ok();
                    writeln!(out, "  store i64 {}, ptr %r{}_f{}_ptr", fv_i64, r, i).ok();
                }
                writeln!(out, "  %r{}_0 = insertvalue {} undef, i64 %r{}_tag, 0", r, en_ty, r).ok();
                writeln!(out, "  %r{}_1 = insertvalue {} %r{}_0, ptr {}, 1", r, en_ty, r, arena_ptr).ok();
                let arena_ptr2 = ctx.arena_alloc(16, out); // {i64, ptr} = 16B
                writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr2).ok();
                writeln!(out, "  store {} %r{}_1, ptr %r{}_cast", en_ty, r, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
            } else {
                let max_fields = types.enums.iter().find(|e| e.name == *enum_name)
                    .map(|e| e.variants.iter().map(|v| v.fields.len()).max().unwrap_or(1))
                    .unwrap_or(1);
                writeln!(out, "  %r{}_0 = insertvalue {} undef, i64 %r{}_tag, 0", r, en_ty, r).ok();
                if max_fields > 1 {
                    // Multi-payload: build sub-struct, then insert at field 1
                    let pl_ty = format!("{{ {} }}", (0..max_fields).map(|_| "i64").collect::<Vec<_>>().join(", "));
                    if fields.is_empty() {
                        writeln!(out, "  %r{}_pl = insertvalue {} undef, i64 0, 0", r, pl_ty).ok();
                        for fi in 1..max_fields {
                            writeln!(out, "  %r{}_pl{} = insertvalue {} %r{}_pl, i64 0, {}", r, fi, pl_ty, r, fi).ok();
                        }
                        let pl_final = if max_fields > 1 { format!("%r{}_pl{}", r, max_fields - 1) } else { format!("%r{}_pl", r) };
                        writeln!(out, "  %r{}_1 = insertvalue {} %r{}_0, {} {}, 1", r, en_ty, r, pl_ty, pl_final).ok();
                    } else {
                        let fv0_i64 = as_i64(r * 1000 + 1, fields[0], out, ctx);
                        writeln!(out, "  %r{}_pl0 = insertvalue {} undef, i64 {}, 0", r, pl_ty, fv0_i64).ok();
                        let mut pl_prev = format!("%r{}_pl0", r);
                        for (i, fv) in fields.iter().skip(1).enumerate() {
                            let fi = i + 1;
                            let fv_i64 = as_i64(r * 1000 + fi + 1, *fv, out, ctx);
                            let pl_next = format!("%r{}_pl{}", r, fi);
                            writeln!(out, "  {} = insertvalue {} {}, i64 {}, {}", pl_next, pl_ty, pl_prev, fv_i64, fi).ok();
                            pl_prev = pl_next;
                        }
                        for fi in fields.len()..max_fields {
                            let pl_next = format!("%r{}_pl{}", r, fi);
                            writeln!(out, "  {} = insertvalue {} {}, i64 0, {}", pl_next, pl_ty, pl_prev, fi).ok();
                            pl_prev = pl_next;
                        }
                        writeln!(out, "  %r{}_1 = insertvalue {} %r{}_0, {} {}, 1", r, en_ty, r, pl_ty, pl_prev).ok();
                    }
                    let arena_ptr = ctx.arena_alloc(8 + max_fields * 8, out);
                    writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
                    writeln!(out, "  store {} %r{}_1, ptr %r{}_cast", en_ty, r, r).ok();
                    writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
                } else {
                let mut prev = format!("%r{}_0", r);
                for (i, fv) in fields.iter().enumerate() {
                    let next = format!("%r{}_{}", r, i + 1);
                    let fv_i64 = as_i64(r * 1000 + i + 1, *fv, out, ctx);
                    writeln!(out, "  {} = insertvalue {} {}, i64 {}, {}", next, en_ty, prev, fv_i64, i + 1).ok();
                    prev = next;
                }
                let size = 8 + fields.len() * 8;
                let arena_ptr = ctx.arena_alloc(size, out);
                writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
                writeln!(out, "  store {} {}, ptr %r{}_cast", en_ty, prev, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
                }
            }
        }
        Instr::EnumDisc(r, reg) => {
            ctx.set_reg(*r, IrType::Int);
            match ctx.reg_ty(reg) {
                IrType::Enum(name) | IrType::Struct(name) => {
                    let is_opaque = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if is_opaque { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
                    else {
                        let base_ty = ctx.reg_llvm_ty(reg);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, reg).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, 0", r, base_ty, r).ok();
                    }
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
            }
        }
        Instr::EnumProj(r, _ty, _enum_name, _variant, idx, reg) => {
            ctx.set_reg(*r, IrType::Int);
            match ctx.reg_ty(reg) {
                IrType::Enum(name) | IrType::Struct(name) => {
                    let is_opaque = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if is_opaque { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
                    else if ctx.is_recursive_enum(name) {
                        let base_ty = ctx.reg_llvm_ty(reg);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, reg).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        writeln!(out, "  %r{}_pl = extractvalue {} %r{}_p, 1", r, base_ty, r).ok();
                        writeln!(out, "  %r{}_fp = getelementptr i64, ptr %r{}_pl, i64 {}", r, r, idx).ok();
                        writeln!(out, "  %r{} = load i64, ptr %r{}_fp", r, r).ok();
                    } else {
                        let base_ty = ctx.reg_llvm_ty(reg);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, reg).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        let max_fields = types.enums.iter().find(|e| e.name == *name)
                            .map(|e| e.variants.iter().map(|v| v.fields.len()).max().unwrap_or(1))
                            .unwrap_or(1);
                        if max_fields > 1 {
                            let pl_ty = format!("{{ {} }}", (0..max_fields).map(|_| "i64").collect::<Vec<_>>().join(", "));
                            writeln!(out, "  %r{}_pl = extractvalue {} %r{}_p, 1", r, base_ty, r).ok();
                            writeln!(out, "  %r{} = extractvalue {} %r{}_pl, {}", r, pl_ty, r, idx).ok();
                        } else {
                            writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, base_ty, r, idx + 1).ok();
                        }
                    }
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, reg).ok(); }
            }
        }
        Instr::Field(r, base, idx, field_ty) => {
            // Set result register type to the actual field type so downstream
            // StructUpdate/Field can generate correct LLVM aggregate operations.
            let field_ir_ty = match ctx.reg_ty(base) {
                IrType::Struct(name) => types.struct_field_type(name, *idx).unwrap_or(IrType::Int),
                _ => field_ty.clone(),
            };
            ctx.set_reg(*r, field_ir_ty);
            match ctx.reg_ty(base) {
                IrType::Tuple(_) => {
                    let n = match ctx.reg_ty(base) { IrType::Tuple(ts) => ts.len(), _ => 1 };
                    let tup_ty = format!("{{ {} }}", (0..n).map(|_| "i64").collect::<Vec<_>>().join(", "));
                    writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
                    writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, tup_ty, r).ok();
                    writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, tup_ty, r, idx).ok();
                    return Ok(());
                }
                IrType::Struct(name) | IrType::Enum(name) => {
                    if ctx.is_recursive_enum(name) {
                        let base_ty = ctx.reg_llvm_ty(base);
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, base_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, base_ty, r, idx).ok();
                        return Ok(());
                    }
                    let is_generic = name.len() == 1 && name.chars().next().map_or(false, |c| c.is_ascii_uppercase());
                    if !is_generic {
                        let st_ty = if matches!(ctx.reg_ty(base), IrType::Enum(_)) { format!("%enum.{}", name) } else { format!("%struct.{}", name) };
                        writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
                        writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, st_ty, r).ok();
                        writeln!(out, "  %r{} = extractvalue {} %r{}_p, {}", r, st_ty, r, idx).ok();
                    } else {
                        writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok();
                    }
                }
                IrType::Int => {
                    writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
                    writeln!(out, "  %r{}_ep = getelementptr i64, ptr %r{}_ptr, i32 {}", r, r, idx).ok();
                    writeln!(out, "  %r{} = load i64, ptr %r{}_ep", r, r).ok();
                }
                _ => { writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok(); }
            }
        }
        Instr::StructUpdate(r, base, fidx, val, s_ty, _in_place) => {
            ctx.set_reg(*r, s_ty.clone());
            // Determine the LLVM struct type: prefer s_ty from the instruction,
            // fall back to reg_llvm_ty(base) for the edge case where s_ty
            // defaulted to %tuple/i64 due to missing reg_struct info.
            let struct_ty = match &s_ty {
                IrType::Struct(name) if name == "%tuple" => {
                    let n = match ctx.reg_ty(base) { IrType::Tuple(ts) => ts.len(), _ => 2 };
                    format!("{{ {} }}", (0..n).map(|_| "i64").collect::<Vec<_>>().join(", "))
                }
                IrType::Struct(name) => {
                    if ctx.enum_names.contains(name) {
                        format!("%enum.{}", name)
                    } else {
                        format!("%struct.{}", name)
                    }
                }
                _ => ctx.reg_llvm_ty(base),
            };
            writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
            writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, struct_ty, r).ok();
            writeln!(out, "  %r{}_upd = insertvalue {} %r{}_p, i64 %r{}, {}", r, struct_ty, r, val, fidx).ok();
            let n = match &s_ty { IrType::Struct(name) => {
                types.structs.iter().find(|s| s.name == *name).map(|s| s.fields.len()).unwrap_or(1)
            }, _ => match ctx.reg_ty(base) {
                IrType::Tuple(ts) => ts.len(),
                IrType::Struct(name) => types.structs.iter().find(|s| s.name == *name).map(|s| s.fields.len()).unwrap_or(1),
                _ => 1,
            }};
            let arena_ptr = ctx.arena_alloc(n * 8, out);
            writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
            writeln!(out, "  store {} %r{}_upd, ptr %r{}_cast", struct_ty, r, r).ok();
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
        }
        Instr::ArrayLit(r, ty, elems) => {
            ctx.set_reg(*r, ty.clone());
            let n = elems.len();
            let esize = 8;
            let size = n * esize;
            let arena_ptr = ctx.arena_alloc(size, out);
            for (i, e) in elems.iter().enumerate() {
                writeln!(out, "  %r{}_ep{} = getelementptr i8, ptr {}, i32 {}", r, i, arena_ptr, (i * esize) as i32).ok();
                writeln!(out, "  store i64 %r{}, ptr %r{}_ep{}", e, r, i).ok();
            }
            writeln!(out, "  %r{} = ptrtoint ptr {} to i64", r, arena_ptr).ok();
        }
        Instr::ArrayFill(r, ty, val, n) => {
            ctx.set_reg(*r, ty.clone());
            let esize = 8;
            let size = *n as usize * esize;
            let arena_ptr = ctx.arena_alloc(size, out);
            for i in 0..*n {
                writeln!(out, "  %r{}_ep{} = getelementptr i8, ptr {}, i32 {}", r, i, arena_ptr, i * esize).ok();
                writeln!(out, "  store i64 %r{}, ptr %r{}_ep{}", val, r, i).ok();
            }
            writeln!(out, "  %r{} = ptrtoint ptr {} to i64", r, arena_ptr).ok();
        }
        Instr::ArrayAccess(r, _ty, arr, idx) => {
            ctx.set_reg(*r, match ctx.reg_ty(arr) { IrType::Array(t, _) => (**t).clone(), _ => IrType::Int });
            writeln!(out, "  %r{}_p = inttoptr i64 %r{} to ptr", r, arr).ok();
            writeln!(out, "  %r{}_off = mul i64 %r{}, 8", r, idx).ok();
            writeln!(out, "  %r{}_ep = getelementptr i8, ptr %r{}_p, i64 %r{}_off", r, r, r).ok();
            writeln!(out, "  %r{}_raw = load i64, ptr %r{}_ep", r, r).ok();
            match ctx.reg_ty(r) {
                IrType::Bool => { writeln!(out, "  %r{} = trunc i64 %r{}_raw to i1", r, r).ok(); }
                _ => { writeln!(out, "  %r{} = add i64 %r{}_raw, 0", r, r).ok(); }
            }
        }
        Instr::ArrayUpdate(r, _ty, arr, idx, val, _in_place) => {
            let elem_ty = match ctx.reg_ty(arr) { IrType::Array(t, _) => ir_type_to_llvm(t), _ => "i64".into() };
            let esize = if elem_ty == "i1" { "1" } else if elem_ty == "i32" { "4" } else { "8" };
            ctx.set_reg(*r, ctx.reg_ty(arr).clone());
            writeln!(out, "  %r{}_p = inttoptr i64 %r{} to ptr", r, arr).ok();
            writeln!(out, "  %r{}_off = mul i64 %r{}, {}", r, idx, esize).ok();
            writeln!(out, "  %r{}_ep = getelementptr i8, ptr %r{}_p, i64 %r{}_off", r, r, r).ok();
            let fv_i64 = as_i64(r * 1000, *val, out, ctx);
            writeln!(out, "  store i64 {}, ptr %r{}_ep", fv_i64, r).ok();
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, arr).ok();
        }
        Instr::TupleLit(r, ty, elems) => {
            ctx.set_reg(*r, ty.clone());
            if elems.is_empty() {
                writeln!(out, "  %r{} = add i64 0, 0", r).ok();
                return Ok(());
            }
            let struct_ty = format!("{{ {} }}", (0..elems.len()).map(|_| "i64").collect::<Vec<_>>().join(", "));
            // Build the struct value inline
            let f: Vec<String> = elems.iter().map(|e| format!("i64 %r{}", e)).collect();
            writeln!(out, "  %r{}_0 = insertvalue {} undef, {}, 0", r, struct_ty, f.first().unwrap_or(&"i64 0".into())).ok();
            let mut prev = format!("%r{}_0", r);
            for (i, ev) in elems.iter().skip(1).enumerate() {
                let idx = i + 1;
                let next = format!("%r{}_{}", r, idx);
                writeln!(out, "  {} = insertvalue {} {}, i64 %r{}, {}", next, struct_ty, prev, ev, idx).ok();
                prev = next;
            }
            // Arena-allocate and store, like structs
            let arena_ptr = ctx.arena_alloc(elems.len() * 8, out);
            writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
            writeln!(out, "  store {} {}, ptr %r{}_cast", struct_ty, prev, r).ok();
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
        }
        Instr::TupleUpdate(r, tup, idx, val, _in_place) => {
            ctx.set_reg(*r, ctx.reg_ty(tup).clone());
            // Arena-allocated tuple: load, update, store back
            let n = match ctx.reg_ty(tup) { IrType::Tuple(ts) => ts.len(), _ => 1 };
            let struct_ty = format!("{{ {} }}", (0..n).map(|_| "i64").collect::<Vec<_>>().join(", "));
            writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, tup).ok();
            writeln!(out, "  %r{}_p = load {}, ptr %r{}_ptr", r, struct_ty, r).ok();
            writeln!(out, "  %r{}_upd = insertvalue {} %r{}_p, i64 %r{}, {}", r, struct_ty, r, val, idx).ok();
            let arena_ptr = ctx.arena_alloc(n * 8, out);
            writeln!(out, "  %r{}_cast = bitcast ptr {} to ptr", r, arena_ptr).ok();
            writeln!(out, "  store {} %r{}_upd, ptr %r{}_cast", struct_ty, r, r).ok();
            writeln!(out, "  %r{} = ptrtoint ptr %r{}_cast to i64", r, r).ok();
        }
        Instr::Fetch(r, base, path) => {
            writeln!(out, "  %r{}_ptr = inttoptr i64 %r{} to ptr", r, base).ok();
            let mut prev = format!("%r{}_ptr", r);
            for (i, accessor) in path.iter().enumerate() {
                match accessor {
                    Accessor::Field(name) => {
                        let next = format!("%r{}_f{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i32 {}", next, prev, name.len()).ok();
                        prev = next;
                    }
                    Accessor::Index(reg) => {
                        let next = format!("%r{}_i{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i64 %r{}", next, prev, reg).ok();
                        prev = next;
                    }
                    Accessor::TupleIndex(idx) => {
                        writeln!(out, "  %r{} = extractvalue i64 %r{}, {}", r, base, idx).ok();
                        return Ok(());
                    }
                }
            }
            writeln!(out, "  %r{} = load i64, ptr {}", r, prev).ok();
        }
        Instr::Place(r, base, path, val) => {
            let mut prev = format!("%r{}_p", r);
            writeln!(out, "  {} = inttoptr i64 %r{} to ptr", prev, base).ok();
            for (i, accessor) in path.iter().enumerate() {
                match accessor {
                    Accessor::Field(name) => {
                        let next = format!("%r{}_f{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i32 {}", next, prev, name.len()).ok();
                        prev = next;
                    }
                    Accessor::Index(reg) => {
                        let next = format!("%r{}_i{}", r, i);
                        writeln!(out, "  {} = getelementptr i64, ptr {}, i64 %r{}", next, prev, reg).ok();
                        prev = next;
                    }
                    Accessor::TupleIndex(idx) => {
                        writeln!(out, "  %r{} = insertvalue i64 %r{}, i64 %r{}, {}", r, base, val, idx).ok();
                        return Ok(());
                    }
                }
            }
            writeln!(out, "  store i64 %r{}, ptr {}", val, prev).ok();
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, base).ok();
        }
        Instr::Lambda(r, fn_name, captures) => {
            ctx.set_reg(*r, IrType::Int);
            let id = ctx.register_closure(fn_name, captures.len());
            if captures.is_empty() {
                let cls_ptr = ctx.arena_alloc(16, out);
                writeln!(out, "  %r{}_idp = getelementptr i64, ptr {}, i32 0", r, cls_ptr).ok();
                writeln!(out, "  store i64 {}, ptr %r{}_idp", id, r).ok();
                writeln!(out, "  %r{}_evp = getelementptr i64, ptr {}, i32 1", r, cls_ptr).ok();
                writeln!(out, "  store i64 0, ptr %r{}_evp", r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr {} to i64", r, cls_ptr).ok();
                ctx.closure_env.insert(*r, ClosureEnv { fn_name: fn_name.clone(), capture_count: 0, cap_ptr_ssa: "0".into() });
            } else {
                let cap_ptr = ctx.arena_alloc(captures.len() * 8, out);
                for (i, cap_reg) in captures.iter().enumerate() {
                    writeln!(out, "  %r{}_c{} = getelementptr i64, ptr {}, i32 {}", r, i, cap_ptr, i).ok();
                    writeln!(out, "  store i64 %r{}, ptr %r{}_c{}", cap_reg, r, i).ok();
                }
                let cap_i64 = format!("%r{}_cap_i64", r);
                writeln!(out, "  {} = ptrtoint ptr {} to i64", cap_i64, cap_ptr).ok();
                let cls_ptr = ctx.arena_alloc(16, out);
                writeln!(out, "  %r{}_idp = getelementptr i64, ptr {}, i32 0", r, cls_ptr).ok();
                writeln!(out, "  store i64 {}, ptr %r{}_idp", id, r).ok();
                writeln!(out, "  %r{}_evp = getelementptr i64, ptr {}, i32 1", r, cls_ptr).ok();
                writeln!(out, "  store i64 {}, ptr %r{}_evp", cap_i64, r).ok();
                writeln!(out, "  %r{} = ptrtoint ptr {} to i64", r, cls_ptr).ok();
                ctx.closure_env.insert(*r, ClosureEnv { fn_name: fn_name.clone(), capture_count: captures.len(), cap_ptr_ssa: cap_i64 });
            }
        }
        Instr::Move(r, from) => {
            writeln!(out, "  %r{} = add i64 %r{}, 0", r, from).ok();
        }
        Instr::Update(_r, _target) => {
            // LLVM thunks are stateless — Update is a no-op.
            // The thunk stores the closure value on first evaluation;
            // subsequent Forces reuse the cached value. LLVM doesn't
            // use this caching mechanism; each Force re-evaluates.
        }
        _ => { writeln!(out, "  ; unimplemented instruction").ok(); }
    }
    Ok(())
}

fn emit_terminator(t: &Terminator, ret_ty: &IrType, out: &mut String, ctx: &LlvmCtx, is_main: bool) -> Result<(), String> {
    match t {
        Terminator::Ret(r) => {
            if is_main {
                writeln!(out, "  ret i32 0").ok();
            } else if *ret_ty == IrType::Unit {
                writeln!(out, "  ret void").ok();
            } else {
                let rt = llvm_boundary_type(ret_ty);
                // If register type doesn't match declared return type, convert
                let val = match (ret_ty, ctx.reg_ty(r)) {
                    (IrType::Int, IrType::Char) => { writeln!(out, "  %r{}_ret = zext i32 %r{} to i64", r, r).ok(); format!("%r{}_ret", r) }
                    _ => format!("%r{}", r),
                };
                writeln!(out, "  ret {} {}", rt, val).ok();
            }
        }
        Terminator::Br(cond, t_label, f_label) => {
            writeln!(out, "  br i1 %r{}, label %{}, label %{}", cond, t_label, f_label).ok();
        }
        Terminator::Jmp(label) => {
            writeln!(out, "  br label %{}", label).ok();
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_simple_module() {
        let mut module = Module::new();
        let mut f = Fn::new("main".into(), vec![], IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(42)));
        block.terminator = Terminator::Ret(0);
        f.blocks.push(block);
        module.fns.push(f);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("define i32 @main"));
        assert!(llvm.contains("ret i32 0"));
    }

    #[test]
    fn generate_with_thunk() {
        let mut module = Module::new();
        let mut t = Thunk::new("x".into(), IrType::Int);
        let mut block = BasicBlock::new("entry".into());
        block.instrs.push(Instr::Lit(0, LitValue::Int(2026)));
        block.terminator = Terminator::Ret(0);
        t.blocks.push(block);
        module.thunks.push(t);
        let llvm = generate(&module).unwrap();
        assert!(llvm.contains("@x.cell"));
        assert!(llvm.contains("define i64 @force_x"));
    }
}
