[book]
authors = ["Dew Contributors"]
language = "en"
multilingual = false
src = "src"
title = "The Dew Language Book"
description = "A minimal functional language with affine types, implicit lazy evaluation, and first-class closures."
build-dir = "book"

[output.html]
site-url = "/dew/book/en/"
git-repository-url = "https://github.com/ACM-Class-2026-Spring/dew"

[output.html.fold]
enable = true
level = 1
